In [1]:
import torch
import torch.nn.functional as F
import numpy as np

In [8]:
# 测试expand方法的作用
A = torch.rand(5,2,1)
print(A.shape)
print(A)
B = A.permute(0,2,1)
print(B.shape)
print(B)
C = B.expand(-1,2,-1) # 扩展就是把哪个维度上的值复制几份
print(C.shape)
print(C)

torch.Size([5, 2, 1])
tensor([[[0.7809],
         [0.2537]],

        [[0.9649],
         [0.1673]],

        [[0.8156],
         [0.7914]],

        [[0.3099],
         [0.2186]],

        [[0.1139],
         [0.0593]]])
torch.Size([5, 1, 2])
tensor([[[0.7809, 0.2537]],

        [[0.9649, 0.1673]],

        [[0.8156, 0.7914]],

        [[0.3099, 0.2186]],

        [[0.1139, 0.0593]]])
torch.Size([5, 2, 2])
tensor([[[0.7809, 0.2537],
         [0.7809, 0.2537]],

        [[0.9649, 0.1673],
         [0.9649, 0.1673]],

        [[0.8156, 0.7914],
         [0.8156, 0.7914]],

        [[0.3099, 0.2186],
         [0.3099, 0.2186]],

        [[0.1139, 0.0593],
         [0.1139, 0.0593]]])


In [12]:
# stack操作测试
A = [torch.rand(3,2),torch.rand(3,2)]
print(A)
stackA = torch.stack(A,-1)
print(stackA.shape)
stackA 

[tensor([[0.3635, 0.6664],
        [0.9040, 0.8429],
        [0.2058, 0.5958]]), tensor([[0.4231, 0.3937],
        [0.9176, 0.7017],
        [0.6273, 0.0342]])]
torch.Size([3, 2, 2])


tensor([[[0.3635, 0.4231],
         [0.6664, 0.3937]],

        [[0.9040, 0.9176],
         [0.8429, 0.7017]],

        [[0.2058, 0.6273],
         [0.5958, 0.0342]]])

In [27]:
# F的softmax的作用
A = torch.tensor([[2.,5.],
                 [3.,5.]])
print(A.shape)
print(A)
print(F.softmax(A,dim=1))

torch.Size([2, 2])
tensor([[2., 5.],
        [3., 5.]])
tensor([[0.0474, 0.9526],
        [0.1192, 0.8808]])


In [34]:
#torch.max的测试
A = torch.rand(5,2,3)
print(A.shape)
print(A)
maxA2 = torch.max(A,dim=2)
# print(maxA2.shape)
print(maxA2)
print(maxA2[0].shape)
print(maxA2[0])

torch.Size([5, 2, 3])
tensor([[[0.5565, 0.5760, 0.4266],
         [0.9779, 0.6552, 0.6916]],

        [[0.0872, 0.1673, 0.2115],
         [0.7215, 0.2807, 0.1919]],

        [[0.3809, 0.5997, 0.8505],
         [0.6466, 0.4969, 0.8279]],

        [[0.9324, 0.3479, 0.8052],
         [0.1896, 0.7805, 0.2646]],

        [[0.0463, 0.3359, 0.5810],
         [0.5031, 0.5021, 0.3640]]])
torch.return_types.max(
values=tensor([[0.5760, 0.9779],
        [0.2115, 0.7215],
        [0.8505, 0.8279],
        [0.9324, 0.7805],
        [0.5810, 0.5031]]),
indices=tensor([[1, 0],
        [2, 0],
        [2, 2],
        [0, 1],
        [2, 0]]))
torch.Size([5, 2])
tensor([[0.5760, 0.9779],
        [0.2115, 0.7215],
        [0.8505, 0.8279],
        [0.9324, 0.7805],
        [0.5810, 0.5031]])


In [22]:
# power操作
np.power(4,0.5) #  4的0.5次方，在基于负采样的的取词比例中可以用到

2.0

In [26]:
# Self Attention的Q,K,V 向量化矩阵计算
X = torch.rand(1,2,4)
print(X)
Wq = torch.rand(1,4,3)
print(Wq)
Wk = torch.rand(1,4,3)
print(Wk)
Wv = torch.rand(1,4,3)
print(Wv)

print()
Q = torch.bmm(X,Wq)
print("Q的shape",Q.shape)
print(Q)
K = torch.bmm(X,Wk)
print("K的shape",K.shape)
print(K)
V = torch.bmm(X,Wv)
print("V的shape",V.shape)
print(V)

attn1 = torch.bmm(Q,K.transpose(2,1))
print("attn1的shape:",attn1.shape)
print(attn1)

attn2 = attn1 / 8.0
print("attn2的shape:",attn2.shape)
print(attn2)

attn3 = torch.nn.Softmax(dim=2)(attn2)
print("attn3的shape:",attn3.shape)
print(attn3)

output = torch.bmm(attn3,V)
print(output)

tensor([[[0.0295, 0.2603, 0.8781, 0.3195],
         [0.6234, 0.3218, 0.2369, 0.1595]]])
tensor([[[0.8979, 0.4294, 0.6101],
         [0.6974, 0.4764, 0.1956],
         [0.4635, 0.3978, 0.5712],
         [0.0248, 0.5652, 0.2259]]])
tensor([[[0.7361, 0.5180, 0.6232],
         [0.9799, 0.0461, 0.6374],
         [0.2546, 0.6357, 0.1136],
         [0.1184, 0.0487, 0.7997]]])
tensor([[[0.4151, 0.9929, 0.2187],
         [0.0835, 0.5420, 0.9282],
         [0.5881, 0.4215, 0.6292],
         [0.1119, 0.4513, 0.1579]]])

Q的shape torch.Size([1, 2, 3])
tensor([[[0.6230, 0.6666, 0.6427],
         [0.8979, 0.6053, 0.6146]]])
K的shape torch.Size([1, 2, 3])
tensor([[[0.5383, 0.6011, 0.5396],
         [0.8534, 0.4961, 0.7480]]])
V的shape torch.Size([1, 2, 3])
tensor([[[0.5861, 0.6848, 0.8511],
         [0.4428, 0.9652, 0.6092]]])
attn1的shape: torch.Size([1, 2, 2])
tensor([[[1.0828, 1.3431],
         [1.1788, 1.5263]]])
attn2的shape: torch.Size([1, 2, 2])
tensor([[[0.1353, 0.1679],
         [0.1473, 0.1908]]

In [7]:
# argmax()测试
A = torch.rand(5,3)
print(A)
print(A.argmax().item()) # 最大的那个值在矩阵被打平为一维List时中的索引位置
print(A[0].argmax().item()) # 最大的那个值在列表中的索引位置

tensor([[0.5647, 0.1576, 0.6414],
        [0.3598, 0.8444, 0.0225],
        [0.6837, 0.0784, 0.2989],
        [0.4277, 0.8252, 0.0287],
        [0.2266, 0.9268, 0.3346]])
13
2
