In [30]:
import torch
import torch.nn.functional as F
import numpy as np

In [8]:
# 测试expand方法的作用
A = torch.rand(5,2,1)
print(A.shape)
print(A)
B = A.permute(0,2,1)
print(B.shape)
print(B)
C = B.expand(-1,2,-1) # 扩展就是把哪个维度上的值复制几份
print(C.shape)
print(C)

torch.Size([5, 2, 1])
tensor([[[0.7809],
         [0.2537]],

        [[0.9649],
         [0.1673]],

        [[0.8156],
         [0.7914]],

        [[0.3099],
         [0.2186]],

        [[0.1139],
         [0.0593]]])
torch.Size([5, 1, 2])
tensor([[[0.7809, 0.2537]],

        [[0.9649, 0.1673]],

        [[0.8156, 0.7914]],

        [[0.3099, 0.2186]],

        [[0.1139, 0.0593]]])
torch.Size([5, 2, 2])
tensor([[[0.7809, 0.2537],
         [0.7809, 0.2537]],

        [[0.9649, 0.1673],
         [0.9649, 0.1673]],

        [[0.8156, 0.7914],
         [0.8156, 0.7914]],

        [[0.3099, 0.2186],
         [0.3099, 0.2186]],

        [[0.1139, 0.0593],
         [0.1139, 0.0593]]])


In [12]:
# stack操作测试
A = [torch.rand(3,2),torch.rand(3,2)]
print(A)
stackA = torch.stack(A,-1)
print(stackA.shape)
stackA 

[tensor([[0.3635, 0.6664],
        [0.9040, 0.8429],
        [0.2058, 0.5958]]), tensor([[0.4231, 0.3937],
        [0.9176, 0.7017],
        [0.6273, 0.0342]])]
torch.Size([3, 2, 2])


tensor([[[0.3635, 0.4231],
         [0.6664, 0.3937]],

        [[0.9040, 0.9176],
         [0.8429, 0.7017]],

        [[0.2058, 0.6273],
         [0.5958, 0.0342]]])

In [27]:
# F的softmax的作用
A = torch.tensor([[2.,5.],
                 [3.,5.]])
print(A.shape)
print(A)
print(F.softmax(A,dim=1))

torch.Size([2, 2])
tensor([[2., 5.],
        [3., 5.]])
tensor([[0.0474, 0.9526],
        [0.1192, 0.8808]])


In [8]:
#torch.max,的测试
A = torch.rand(5,2,3)
print(A.shape)
print(A)
print("===============")
# dim=0 torch.Size([2, 3])取出了第0维度中的所有2*3=6个数相加和最大的那一组数
# dim=1 torch.Size([5, 3])每一组中每一列取最大值构成新的1*3的一组数
# dim=2 torch.Size([5, 2])每一组中每一行取最大值构成新的2*1的一组
maxA2 = torch.max(A,dim=1)
# print(maxA2.shape)
print(maxA2)
print("===============")
print(maxA2[0].shape)
print(maxA2[0])

torch.Size([5, 2, 3])
tensor([[[0.5847, 0.9882, 0.0402],
         [0.3335, 0.5820, 0.9439]],

        [[0.8150, 0.7132, 0.5204],
         [0.9753, 0.1078, 0.1540]],

        [[0.3415, 0.0234, 0.2402],
         [0.5227, 0.4375, 0.7785]],

        [[0.0743, 0.8308, 0.0052],
         [0.7166, 0.3797, 0.4055]],

        [[0.8669, 0.9656, 0.6711],
         [0.1539, 0.7742, 0.6488]]])
torch.return_types.max(
values=tensor([[0.5847, 0.9882, 0.9439],
        [0.9753, 0.7132, 0.5204],
        [0.5227, 0.4375, 0.7785],
        [0.7166, 0.8308, 0.4055],
        [0.8669, 0.9656, 0.6711]]),
indices=tensor([[0, 0, 1],
        [1, 0, 0],
        [1, 1, 1],
        [1, 0, 1],
        [0, 0, 0]]))
torch.Size([5, 3])
tensor([[0.5847, 0.9882, 0.9439],
        [0.9753, 0.7132, 0.5204],
        [0.5227, 0.4375, 0.7785],
        [0.7166, 0.8308, 0.4055],
        [0.8669, 0.9656, 0.6711]])


In [23]:
#torch.max2,的测试
A = torch.randn(3,2)
print(A)
B = torch.randn(3,2)
print(B)
torch.max(A,B,out=A)
print("================")
print(A)
print(B)

tensor([[-1.2861,  1.8419],
        [ 1.0022, -0.1568],
        [-0.4694,  0.9617]])
tensor([[ 1.1856, -1.4431],
        [-0.0639,  0.3934],
        [ 1.1764, -1.4525]])
tensor([[1.1856, 1.8419],
        [1.0022, 0.3934],
        [1.1764, 0.9617]])
tensor([[ 1.1856, -1.4431],
        [-0.0639,  0.3934],
        [ 1.1764, -1.4525]])


In [22]:
# power操作
np.power(4,0.5) #  4的0.5次方，在基于负采样的的取词比例中可以用到

2.0

In [26]:
# Self Attention的Q,K,V 向量化矩阵计算
X = torch.rand(1,2,4)
print(X)
Wq = torch.rand(1,4,3)
print(Wq)
Wk = torch.rand(1,4,3)
print(Wk)
Wv = torch.rand(1,4,3)
print(Wv)

print()
Q = torch.bmm(X,Wq)
print("Q的shape",Q.shape)
print(Q)
K = torch.bmm(X,Wk)
print("K的shape",K.shape)
print(K)
V = torch.bmm(X,Wv)
print("V的shape",V.shape)
print(V)

attn1 = torch.bmm(Q,K.transpose(2,1))
print("attn1的shape:",attn1.shape)
print(attn1)

attn2 = attn1 / 8.0
print("attn2的shape:",attn2.shape)
print(attn2)

attn3 = torch.nn.Softmax(dim=2)(attn2)
print("attn3的shape:",attn3.shape)
print(attn3)

output = torch.bmm(attn3,V)
print(output)

tensor([[[0.0295, 0.2603, 0.8781, 0.3195],
         [0.6234, 0.3218, 0.2369, 0.1595]]])
tensor([[[0.8979, 0.4294, 0.6101],
         [0.6974, 0.4764, 0.1956],
         [0.4635, 0.3978, 0.5712],
         [0.0248, 0.5652, 0.2259]]])
tensor([[[0.7361, 0.5180, 0.6232],
         [0.9799, 0.0461, 0.6374],
         [0.2546, 0.6357, 0.1136],
         [0.1184, 0.0487, 0.7997]]])
tensor([[[0.4151, 0.9929, 0.2187],
         [0.0835, 0.5420, 0.9282],
         [0.5881, 0.4215, 0.6292],
         [0.1119, 0.4513, 0.1579]]])

Q的shape torch.Size([1, 2, 3])
tensor([[[0.6230, 0.6666, 0.6427],
         [0.8979, 0.6053, 0.6146]]])
K的shape torch.Size([1, 2, 3])
tensor([[[0.5383, 0.6011, 0.5396],
         [0.8534, 0.4961, 0.7480]]])
V的shape torch.Size([1, 2, 3])
tensor([[[0.5861, 0.6848, 0.8511],
         [0.4428, 0.9652, 0.6092]]])
attn1的shape: torch.Size([1, 2, 2])
tensor([[[1.0828, 1.3431],
         [1.1788, 1.5263]]])
attn2的shape: torch.Size([1, 2, 2])
tensor([[[0.1353, 0.1679],
         [0.1473, 0.1908]]

In [7]:
# argmax()测试
A = torch.rand(5,3)
print(A)
print(A.argmax().item()) # 最大的那个值在矩阵被打平为一维List时中的索引位置
print(A[0].argmax().item()) # 最大的那个值在列表中的索引位置

tensor([[0.5647, 0.1576, 0.6414],
        [0.3598, 0.8444, 0.0225],
        [0.6837, 0.0784, 0.2989],
        [0.4277, 0.8252, 0.0287],
        [0.2266, 0.9268, 0.3346]])
13
2


In [47]:
# sum测试
A = torch.randn(5,3)
print(A)
sumA = A.sum()
print(sumA)
print(A.size())
sum_to_sizeA = A.sum_to_size(A.size()[0],1) # 这样相当于每行相加
print(sum_to_sizeA)
cumsumA = A.cumsum(0) # 0代表列依次递加，1:代表行依次递加
print("cumsumA:",cumsumA)

tensor([[-0.1464,  1.0439,  0.4604],
        [-0.0702,  1.5683, -0.3675],
        [-0.4626,  0.3654,  0.7164],
        [ 0.7878,  0.6938, -0.7750],
        [-0.4429,  0.6910,  0.4281]])
tensor(4.4905)
torch.Size([5, 3])
tensor([[1.3580],
        [1.1306],
        [0.6191],
        [0.7066],
        [0.6763]])
cumsumA: tensor([[-0.1464,  1.0439,  0.4604],
        [-0.2166,  2.6122,  0.0929],
        [-0.6792,  2.9776,  0.8093],
        [ 0.1086,  3.6714,  0.0343],
        [-0.3343,  4.3624,  0.4625]])


In [60]:
# Data处理测试
from torch.utils.data import (DataLoader, RandomSampler, SequentialSampler,
                              TensorDataset)
trainX = torch.randn(11,5) # 11个样本，每个样本有5个feature [11,5]
trainY = trainX.sum_to_size(trainX.size()[0],1) # [11,1]
print(trainX)
print(trainY)
train_dataset = TensorDataset(trainX,trainY) # 只要传入的tensor的第一个维度值相同即可;
print(train_dataset.__getitem__(0)) # TensorDataset里面是一个tuple，可以用__getitem__(index)来取出某一个tensor

print("==================")
train_sampler_no_replacement = RandomSampler(train_dataset) # 会将原始数据随机打乱
print(len(train_sampler_no_replacement))
for idx,item in enumerate(train_sampler_no_replacement):
    print(idx,item)
print(next(iter(train_sampler_no_replacement)))

print("================")
# replacement表示是否可以重复，num_samples是要取的样本数目(因为可以重复，所以样本数取多少都可以)，默认不填写就是样本总数
train_sampler_with_replacemen = RandomSampler(train_dataset,replacement=True,num_samples=20)
print(len(train_sampler_with_replacemen))
for idx,item in enumerate(train_sampler_with_replacemen):
    print(idx,item)

print("================")
train_dataloader = DataLoader(train_dataset,sampler=train_sampler_no_replacement,batch_size=2)
print(len(train_dataloader)) # 这里总共11个样本，2个一组组成一个batch，最终可以组成11/2 +1 =6个batch
for idx,item in enumerate(train_dataloader):
    print(idx,item)

tensor([[ 1.3479, -1.0443, -0.0359, -0.5181, -1.1864],
        [ 1.0870,  1.9154,  0.0949, -0.0053,  0.7588],
        [ 0.9656, -1.9067,  0.0141, -3.3089, -0.3452],
        [ 0.3732, -1.6621,  0.3642, -0.0252, -0.0075],
        [ 0.6322, -0.5308,  0.7938, -1.0148,  1.3878],
        [-2.0887,  0.1318, -0.2714,  0.0504,  0.0523],
        [ 0.4787,  0.4455,  1.2219, -2.2179,  1.4942],
        [-0.1906,  0.2788,  0.5600,  2.0845, -1.0782],
        [-0.3614, -2.3480, -0.4730, -0.2444,  1.5346],
        [-0.3884,  1.0739,  1.2118, -0.8928, -0.1041],
        [-0.2341,  0.3947,  0.2525,  0.4502,  0.0733]])
tensor([[-1.4368],
        [ 3.8508],
        [-4.5811],
        [-0.9574],
        [ 1.2682],
        [-2.1256],
        [ 1.4223],
        [ 1.6545],
        [-1.8921],
        [ 0.9005],
        [ 0.9366]])
(tensor([ 1.3479, -1.0443, -0.0359, -0.5181, -1.1864]), tensor([-1.4368]))
11
0 0
1 2
2 3
3 9
4 1
5 7
6 8
7 4
8 5
9 10
10 6
8
20
0 0
1 3
2 2
3 8
4 4
5 10
6 6
7 3
8 2
9 1
10 5
11 3
12 4

In [65]:
print(8 // 3)
print(8/3)

2
2.6666666666666665


In [68]:
# max_steps >0；t_total
max_steps = 6
len_train_dataloader = 5 # 分组后的batch数目
gradient_accumulation_steps = 2
num_train_epochs = 20 # 需要训练的epochs
if max_steps > 0:
    t_total = max_steps 
    num_train_epochs = max_steps // (len_train_dataloader // gradient_accumulation_steps) + 1
else:
    t_total = len(train_dataloader) // gradient_accumulation_steps * num_train_epochs
print(num_train_epochs)
print(t_total) 


4
6


In [67]:
# max_steps =0
max_steps = 0
len_train_dataloader = 5 # 分组后的batch数目
gradient_accumulation_steps = 2
num_train_epochs = 20 # 需要训练的epochs
if max_steps > 0:
    t_total = max_steps 
    num_train_epochs = max_steps // (len_train_dataloader // gradient_accumulation_steps) + 1
else:
    t_total = len(train_dataloader) // gradient_accumulation_steps * num_train_epochs
print(num_train_epochs)
print(t_total)

20
60


In [22]:
# is_sparse
A = torch.randn(5,3)
print(A)
print(A.data)
A.data.is_sparse

tensor([[-0.5727,  1.4850, -0.3282],
        [ 1.3668, -0.9526,  1.1699],
        [-1.1580,  0.3889, -1.7746],
        [ 0.8349,  0.0372,  0.1035],
        [-0.9505, -0.2258,  0.4844]])
tensor([[-0.5727,  1.4850, -0.3282],
        [ 1.3668, -0.9526,  1.1699],
        [-1.1580,  0.3889, -1.7746],
        [ 0.8349,  0.0372,  0.1035],
        [-0.9505, -0.2258,  0.4844]])


False

In [37]:
# addcdiv_ 测试
A = torch.Tensor([5,2])
step_size = 0.1
exp_avg = torch.Tensor([3,2])
denom = torch.Tensor([2,3])
A.data.addcdiv(-step_size,exp_avg,denom) 

tensor([4.8500, 1.9333])

In [40]:
# tqdm 进度条trang测试
from tqdm import tqdm, trange 
num_train_epochs = 10
train_iterator = trange(int(num_train_epochs),desc="Epoch")
for item in train_iterator:
    print(item)

Epoch: 100%|██████████| 10/10 [00:00<00:00, 7017.41it/s]

0
1
2
3
4
5
6
7
8
9
