In [11]:
# from _future_ import print_function
import numpy as np
import torch

In [ ]:



#Tensors的初始化




In [20]:
# 构建Tensors，Tensors(张量和numpy中的Array是类似的)
x = torch.empty(5,3) 
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
#构造一个随机初始化的矩阵：
x = torch.rand(5,3)
x

tensor([[0.2544, 0.7975, 0.2602],
        [0.8312, 0.3923, 0.4843],
        [0.2903, 0.6636, 0.9573],
        [0.8015, 0.4656, 0.6307],
        [0.7787, 0.1601, 0.5049]])

In [21]:
#构造一个矩阵全为 0，而且数据类型是 long.
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [29]:
#构造一个张量，直接使用数据：
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [45]:
#创建一个 tensor 基于已经存在的 tensor。
x = x.new_ones(5,3,dtype=torch.double) # 把x重写为5*3矩阵，值全为1的矩阵
print(x)

x = torch.randn_like(x,dtype=torch.float32) # 重写数据类型和随机初始化
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1930,  0.1685,  0.9254],
        [-0.3051, -0.2144,  0.2007],
        [-1.5648,  0.5953,  1.2923],
        [ 0.4512, -0.0543,  0.7637],
        [ 0.0019,  1.2586, -0.2726]])


In [47]:
#获取tensor的维度信息:
x.size()

torch.Size([5, 3])

In [ ]:




#Tensors的操作






In [53]:
#加法: 方式 1
y = torch.rand(5,3)
print(x+y)
#加法: 方式2
print(torch.add(x,y))
#加法: 提供一个输出 tensor 作为参数
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)
#加法: in-place
y.add_(x)
print(y)

tensor([[0.9689, 0.8416, 1.0874],
        [0.9712, 0.8663, 1.4279],
        [1.1317, 0.7663, 0.4892],
        [0.6902, 1.1174, 1.1547],
        [0.9953, 0.8629, 1.5671]])
tensor([[0.9689, 0.8416, 1.0874],
        [0.9712, 0.8663, 1.4279],
        [1.1317, 0.7663, 0.4892],
        [0.6902, 1.1174, 1.1547],
        [0.9953, 0.8629, 1.5671]])
tensor([[0.9689, 0.8416, 1.0874],
        [0.9712, 0.8663, 1.4279],
        [1.1317, 0.7663, 0.4892],
        [0.6902, 1.1174, 1.1547],
        [0.9953, 0.8629, 1.5671]])
tensor([[0.9689, 0.8416, 1.0874],
        [0.9712, 0.8663, 1.4279],
        [1.1317, 0.7663, 0.4892],
        [0.6902, 1.1174, 1.1547],
        [0.9953, 0.8629, 1.5671]])


In [55]:
# 你可以使用标准的  NumPy 类似的索引操作
print(x)
print(x[:,1]) # 取出第二列

tensor([[0.6580, 0.3648, 0.5429],
        [0.9405, 0.0864, 0.8118],
        [0.9224, 0.4878, 0.4246],
        [0.4709, 0.6589, 0.6102],
        [0.1849, 0.7958, 0.7116]])
tensor([0.3648, 0.0864, 0.4878, 0.6589, 0.7958])


In [62]:
#改变大小：如果你想改变一个 tensor 的大小或者形状，你可以使用 torch.view:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # size-1会根据其他维度的变化来进行推断出来：这个相当于把原来的两行合并成新的一行
p = x.view(8,-1) # 这个相当于把原来的每行拆成两行
print(x.size(),y.size(),z.size(),p.size())
print(x,'\n',y,'\n',z,'\n',p)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([8, 2])
tensor([[ 0.2955, -0.9996,  1.1670,  0.7220],
        [ 0.6128, -1.6132, -3.1525, -0.1491],
        [-0.3752, -1.7521,  0.6885, -1.3096],
        [-1.0361, -1.2292,  0.5437,  0.7229]]) 
 tensor([ 0.2955, -0.9996,  1.1670,  0.7220,  0.6128, -1.6132, -3.1525, -0.1491,
        -0.3752, -1.7521,  0.6885, -1.3096, -1.0361, -1.2292,  0.5437,  0.7229]) 
 tensor([[ 0.2955, -0.9996,  1.1670,  0.7220,  0.6128, -1.6132, -3.1525, -0.1491],
        [-0.3752, -1.7521,  0.6885, -1.3096, -1.0361, -1.2292,  0.5437,  0.7229]]) 
 tensor([[ 0.2955, -0.9996],
        [ 1.1670,  0.7220],
        [ 0.6128, -1.6132],
        [-3.1525, -0.1491],
        [-0.3752, -1.7521],
        [ 0.6885, -1.3096],
        [-1.0361, -1.2292],
        [ 0.5437,  0.7229]])


In [67]:
#如果你的 tensor只有一个元素 ，使用 .item() 来获得这个 value 。
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3954])
-1.3954102993011475


In [77]:
dir(x)
x.transpose

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__se

In [105]:
# 转置操作
x = torch.randn(2,1,3)
print(x)
print(x.T) # 默认是第一维和最后一维进行转置
# print(torch.t(x)) # 普通的转置操作,只能进行2维矩阵的转置

print(torch.transpose(x,0,2)) # 由两行(0维)3列(2维)变为了三行(0维)两列(2维度)
print(torch.transpose(x,0,1)) # 由两行(0维)一列(1维)变为了一行(0维)两列(1维度)
print(torch.transpose(x,1,2)) # 有一行（1维）3列(2维)变成了3行(1维)1列（2维）

tensor([[[ 1.5485, -1.4282, -2.0670]],

        [[-0.0609,  0.9265, -1.4946]]])
tensor([[[ 1.5485, -0.0609]],

        [[-1.4282,  0.9265]],

        [[-2.0670, -1.4946]]])
tensor([[[ 1.5485, -0.0609]],

        [[-1.4282,  0.9265]],

        [[-2.0670, -1.4946]]])
tensor([[[ 1.5485, -1.4282, -2.0670],
         [-0.0609,  0.9265, -1.4946]]])
tensor([[[ 1.5485],
         [-1.4282],
         [-2.0670]],

        [[-0.0609],
         [ 0.9265],
         [-1.4946]]])


In [ ]:



#Numpy 与 Tensor 之间相互转换





In [74]:
# Numpy 与 Tensor 之间相互转换
# 注意Torch的Tensor和numpy的Array会共享他们的存储空间，修改一个会导致另外的一个也被修改
# 将tensor转化为Numpy Array：
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

# 当修改了tensor之后，与之相关联的numpy array的值也被修改了
a.add_(1)
print(a)
print(b)

# 将array转换为tensor
c = torch.Tensor(b)
print(c)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.])


In [76]:
# 如果有CUDA，可运行此段代码
# 将使用“torch.device”对象来移动我们的tensors从GPU到我们想去的设备
if torch.cuda.is_available():
    device = torch.device("cuda") # 一个CUDA设备对象
    y = torch.ones_like(x,device=device) # 直接在GPU上创建一个tensor
    x = x.to(device) # 或者直接使用字符串“.to("cuda")”
    z = x+y
    print(z)
    print(z.to("cpu",torch.double)) # ".to"函数同时可以修改数据类型
# 如果安装了CUDA后打印出来的结果
# out
# tensor([0.1252],device=’cuda:0‘)
# tensor([0.1252],dtype=torch.float64)

# 如果是GPU的数据要转成numpy array要先转成cpu数据在转:因为numpy只在cpu上运行
# y.to("cpu").data.numpy()
# 或者 y.cpu().data.numpy()

# model = model.cuda() # 把模型变为cuda()