In [1]:
import numpy as np
print("hello jupyter ")


hello jupyter 


In [2]:
import numpy as np

A = np.array([[0,1,0,1]])
B = np.array([[1,1,0,0]])
C = A^B
print(C)
print(np.sum(C))

[[1 0 0 1]]
2


In [23]:
A = np.round(np.random.random((1,4))*10)
print(A)

[[7. 8. 4. 1.]]


In [63]:
print(round(0.5),round(1.5)) # round虽然是4舍5入，但是要看5前面是偶数还是奇数，如果是偶数等于5被舍去，如果是奇数等于5被进1
A = np.round(np.array([[0.7,0.2,0.5,0.44]])+1)-1 # 所以（0，1）之间的值想让它等于5的时候进位，可以先+1后-1
print(A)

0 2
[[1. 0. 1. 0.]]


In [10]:
A = np.array([[0.7,0.2,0.5,0.44]])+0.5
print(A.astype(int)) # 如果要把矩阵取整，就要用这种方式

[[1 0 1 0]]


In [58]:
A= int(44.5) >> 2 # 移为运算只对整数有效
print(A)

11


In [63]:
import time as time
#ReLU函数测试
A = np.random.random((100000000,1))
time1 = time.time()
B = np.maximum(0,A) # 这种方式效率更快
time2 = time.time()
C = (A+np.abs(A))/2
time3 = time.time()
print(time2-time1)
print(time3-time2)

0.49383997917175293
0.7984409332275391


In [76]:
#测试对ReLU函数求导
A= np.array([[-0.7,-0.2],[2,3]])
A[A>=0] = 1
A[A<0] = 0
B = A
print(B)

[[0. 0.]
 [1. 1.]]


In [31]:
A = np.array([[0.7,0.2,0.5,0.44]])
B = np.array([[0.7,0.2,0.5,0.44]])
print(A*B)

[[0.49   0.04   0.25   0.1936]]


In [47]:
# assert测试：（断言
a = (1,2,3,4)
assert len(a) == 4
A = np.array([[0.7,0.2,0.5,0.44]])
print(A.shape)
assert A.shape ==(1,4) 

(1, 4)


In [9]:
# * 与 np.multiply 的对比
A = np.array([[0.7,0.2],[2,3]])
B = np.array([[1,1],[2,2]])
#如果都是数组，A*B = np.multiply(A,B)
print(A*B)
print(np.multiply(A,B))

#如果把A和B转换成矩阵
matA = np.mat(A)
matB = np.mat(B)
print(matA*matB) # 变成了矩阵乘法运算
print(np.multiply(matA,matB)) # 仍然是对应位置相乘

print(0.1*matA)
print(A[0][0])

[[0.7 0.2]
 [4.  6. ]]
[[0.7 0.2]
 [4.  6. ]]
[[1.1 1.1]
 [8.  8. ]]
[[0.7 0.2]
 [4.  6. ]]
[[0.07 0.02]
 [0.2  0.3 ]]
0.7


In [61]:
# np.power对每一个元素单独求次方
A = np.array([[0.7,0.2],[2,3]])
print(np.power(A,2))

[[0.49 0.04]
 [4.   9.  ]]


In [83]:
#逻辑回归最终代价函数关于第L层输出的偏导dAL
TrainY = np.array([[0.7,0.2],[2,3]])
A2 = np.array([[0.8,0.2],[0.6,0.5]])
R1 = np.divide(-TrainY, A2)
R2 = np.divide(1 - TrainY, 1 - A2)
print(R1)
print(R2)
print(R1+R2)

[[-0.875      -1.        ]
 [-3.33333333 -6.        ]]
[[ 1.5  1. ]
 [-2.5 -4. ]]
[[  0.625        0.        ]
 [ -5.83333333 -10.        ]]


In [7]:
A = np.array([[0.7,0.2,0.5,0.44]])
B = np.array([[0.7,0.2,0.5,0.44]])
assert A.shape == B.shape
print(A[0])

[0.7  0.2  0.5  0.44]


In [10]:
#Normalizing rows 规范化行向量，规范化可以使得所有值的取值在（-1，1）之间，方便梯度递减的更快
A = np.array([[0,3,4],[-3,0,4]])
B = np.linalg.norm(A,axis=1,keepdims=True)
C = A/B
print(B)
print(C)

[[5.]
 [5.]]
[[ 0.   0.6  0.8]
 [-0.6  0.   0.8]]


In [4]:
A = np.array([[0,1,0,1,5],
              [2,5,7,6,8],
              [3,1,4,7,6]])
AX_23 = np.zer
print(A)

[[0 1 0 1 5]
 [2 5 7 6 8]
 [3 1 4 7 6]]
