In [37]:
import numpy as np
import pandas as pd
import tensorflow as tf 
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split


# 注意每次Embedding的参数都不一样，所以必须要把模型存储起来

model = keras.Sequential()
# 1000代表的就是数字的最大上限（原维数），64就是新的维，input_length就是原先的数字最是有多少个1000以内的数字表示的（相当于电影特征就多有20个，每个标签对应一个数字）
model.add(layers.Embedding(1000, 64, input_length=10)) 
# the model will take as input an integer matrix of size (batch,
# input_length).
# the largest integer (i.e. word index) in the input should be no larger
# than 999 (vocabulary size).
# now model.output_shape == (None, 10, 64), where None is the batch
# dimension.

input_array = np.random.randint(1000, size=(5, 10))

model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
assert output_array.shape == (5, 10, 64)


In [40]:
print(input_array.shape)
input_array

(5, 10)


array([[801, 586, 370, 473, 254, 479, 238, 574, 558, 518],
       [978, 500, 549, 374,  56, 133, 541, 749, 423, 478],
       [103, 402, 700, 664, 286, 542, 608, 408, 220, 625],
       [553,  71, 379,  57, 987, 496, 984,  85, 332, 604],
       [943, 141, 809, 851, 522,  16, 642, 673,   5, 344]])

In [39]:
output_array

array([[[-3.58303078e-02,  2.21732296e-02,  7.67959282e-03, ...,
         -2.27753874e-02, -4.39700000e-02,  3.71517055e-02],
        [ 3.07140984e-02, -1.78869739e-02,  2.97933482e-02, ...,
         -4.43289988e-02, -2.34690439e-02, -2.10891850e-02],
        [ 1.44120120e-02,  5.12577593e-04, -3.91242988e-02, ...,
         -2.22520828e-02,  1.04832165e-02, -2.33113766e-03],
        ...,
        [ 2.48895325e-02,  2.44447030e-02, -1.24464259e-02, ...,
         -1.08900890e-02, -3.11716329e-02,  1.54016279e-02],
        [ 2.92023532e-02, -3.48860994e-02, -4.95036244e-02, ...,
          4.82361652e-02, -1.42189749e-02, -4.31963094e-02],
        [ 3.00613381e-02,  1.14235282e-02,  6.57827780e-03, ...,
         -4.79498021e-02,  2.06539892e-02,  4.66136672e-02]],

       [[-3.41877230e-02,  3.55938710e-02, -6.01648167e-03, ...,
          3.42873447e-02,  4.92955185e-02,  9.96784121e-03],
        [-4.77123745e-02, -1.67156458e-02,  1.51599571e-03, ...,
         -1.00509040e-02, -3.39676365e

In [81]:
A = np.array([
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 8, 9]
])
A.shape
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 8, 9]])

In [80]:
modelTest = keras.Sequential()
modelTest.add(layers.Embedding(10000, 10, input_length=3)) #把10000维度one-hot表征向量转换为10维
modelTest.add(layers.Flatten())

In [82]:
# B = keras.utils.to_categorical(A) 
B = modelTest.predict(A)
B.shape

(4, 30)

In [73]:
B

array([[ 0.03222332, -0.01538435, -0.0294154 ,  0.00275028, -0.01968499,
         0.0196338 , -0.02637317, -0.04203292, -0.00853612, -0.00764512,
        -0.03519334,  0.02900324, -0.01623942,  0.01992113, -0.04790735,
         0.03025452, -0.01549869, -0.04034015,  0.04972622,  0.04618759,
        -0.0376073 ,  0.01642794,  0.01550103, -0.02188612, -0.03836253,
        -0.03619291,  0.0304672 , -0.0182756 ,  0.02197685,  0.01167438],
       [-0.04205913,  0.01285075,  0.02505298,  0.00139233, -0.00128015,
        -0.03229662,  0.02490301,  0.03601966, -0.04203685,  0.03646943,
        -0.00155235,  0.00683843,  0.02253766,  0.01504798,  0.03856174,
         0.04102427, -0.025964  ,  0.01823201, -0.04883213, -0.00456537,
        -0.03897655, -0.04386648,  0.00076225,  0.01399194,  0.04040116,
        -0.03509635,  0.04888714, -0.02824233,  0.03517615,  0.03624122],
       [-0.02265866, -0.01201319, -0.02411095, -0.00593864,  0.03972992,
         0.03560576, -0.04357224, -0.00859133,  0