In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import optimizers,layers 
import h5py

print(tf.version)

model = keras.models.load_model('/Users/zhenwuzhou/.keras/models/predict_rats.h5')
weights = model.weights

<module 'tensorflow_core._api.v2.version' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/_api/v2/version/__init__.py'>


In [2]:
print(len(weights))
for weight in weights:
    print(weight)

17
<tf.Variable 'dense_45/kernel:0' shape=(2, 32) dtype=float32, numpy=
array([[-0.36772326,  0.11052821,  0.4302168 ,  0.03808226, -0.29203048,
        -0.37670633,  0.0127207 ,  0.19756639,  0.21416482,  0.2075992 ,
         0.43525344, -0.414097  , -0.02086446, -0.17753984, -0.3955018 ,
        -0.19185111, -0.2615066 , -0.2925689 ,  0.18286143,  0.35557902,
        -0.09045795,  0.20604321,  0.2036176 ,  0.12705906,  0.02751337,
        -0.0582113 ,  0.13433956,  0.15616551, -0.38680124,  0.06747997,
         0.08443611,  0.51238525],
       [ 0.36376187,  0.39569628,  0.21413788, -0.17952503, -0.16829416,
         0.32392773, -0.12340137, -0.32866487, -0.3167234 ,  0.14686733,
        -0.22387283, -0.02055317, -0.05080616, -0.01986822,  0.07919863,
        -0.37974125, -0.00891706,  0.36286053, -0.28813538,  0.11391834,
        -0.3096512 ,  0.02823026, -0.39303914,  0.23246393,  0.50773937,
         0.26236776, -0.10813579, -0.33987853, -0.38236704,  0.18713507,
         0.260964

In [70]:
# 构建用来预测用户特征的模型
input_users = layers.Input(shape=(2,))
layerU1 = layers.Dense(32,activation='relu')
layerU1(input_users)
layerU1.set_weights([tf.transpose(weights[0]).numpy().T,tf.transpose(weights[1]).numpy().T])
U1 = layerU1(input_users)

layerU2 = layers.Dense(16,activation='relu')
layerU2(U1)
layerU2.set_weights([tf.transpose(weights[4]).numpy().T,tf.transpose(weights[5]).numpy().T])
U2 = layerU2(U1)

layerU3 = layers.Dense(16,activation='relu')
layerU3(U2)
layerU3.set_weights([tf.transpose(weights[8]).numpy().T,tf.transpose(weights[9]).numpy().T])
U3 = layerU3(U2)

layerU4 = layers.Dense(8,activation='relu')
layerU4(U3)
layerU4.set_weights([tf.transpose(weights[12]).numpy().T,tf.transpose(weights[13]).numpy().T])
U4 = layerU4(U3)

modelUserFeature = keras.models.Model(inputs=[input_users],outputs=U4)



In [5]:
# 我们定义3个用户及他们的用数字化表示的特征(职业：学生，白领，科学家；  年龄段：18岁以下，18-35岁，35岁以上)：
#用户U1的特征[1,1]（16岁的学生）,用户U2的特征[2,2](25岁的白领),用户U3的特征[3,3]（35岁的科学家）
users = np.array([
    [1,1],
    [2,2],
    [3,3]
])
modelUserFeature.predict([users])

array([[1.1035378 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.18192047, 7.096562  ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.52667445, 4.0124493 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        3.1600454 , 0.94720995, 0.        ]], dtype=float32)

In [69]:
# 构建用来预测电影特征的模型
input_movies = layers.Input(shape=(2,))
layerM1 = layers.Dense(32,activation='relu')
layerM1(input_movies)
layerM1.set_weights([tf.transpose(weights[2]).numpy().T,tf.transpose(weights[3]).numpy().T])
M1 = layerM1(input_movies)

layerM2 = layers.Dense(16,activation='relu')
layerM2(M1)
layerM2.set_weights([tf.transpose(weights[6]).numpy().T,tf.transpose(weights[7]).numpy().T])
M2 = layerM2(M1)

layerM3 = layers.Dense(16,activation='relu')
layerM3(M2)
layerM3.set_weights([tf.transpose(weights[10]).numpy().T,tf.transpose(weights[11]).numpy().T])
M3 = layerM3(M2)

layerM4 = layers.Dense(8,activation='relu')
layerM4(M3)
layerM4.set_weights([tf.transpose(weights[14]).numpy().T,tf.transpose(weights[15]).numpy().T])
M4 = layerM4(M3)

modelMovieFeature = keras.models.Model(inputs=[input_movies],outputs=M4)

In [7]:
# 我们定义3部影视作品及它们的用数字化表示的特征(类型（青春校园，职场生活，科幻世界），年代：10年以内，10以前20年以内，20年以前)：
#影视M1的特征[1,1]《少年派》,影视M2的特征[2,2]《穿普拉达的女王》,电影M3的特征[3,3]《2001太空漫游》
movies = np.array([
    [1,1],
    [2,2],
    [3,3]
])
modelUserFeature.predict([movies])

array([[1.1035378 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.18192047, 7.096562  ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.52667445, 4.0124493 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        3.1600454 , 0.94720995, 0.        ]], dtype=float32)