In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf 
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split

# URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
dataframe = pd.read_csv('/Users/zhenwuzhou/.keras/datasets/heart.csv')

In [6]:
dataframe.head

<bound method NDFrame.head of      age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0     63    1   1       145   233  ...      2.3      3   0       fixed       0
1     67    1   4       160   286  ...      1.5      2   3      normal       1
2     67    1   4       120   229  ...      2.6      2   2  reversible       0
3     37    1   3       130   250  ...      3.5      3   0      normal       0
4     41    0   2       130   204  ...      1.4      1   0      normal       0
..   ...  ...  ..       ...   ...  ...      ...    ...  ..         ...     ...
298   52    1   1       118   186  ...      0.0      2   0       fixed       0
299   43    0   4       132   341  ...      3.0      2   0  reversible       1
300   65    1   4       135   254  ...      2.8      2   1  reversible       1
301   48    1   4       130   256  ...      0.0      1   2  reversible       1
302   63    0   4       150   407  ...      4.0      2   3  reversible       1

[303 rows x 14 column

In [7]:
# 分割训练集，验证集，测试集
train,test = train_test_split(dataframe,test_size=0.2)
train,val = train_test_split(train,test_size=0.2)
print(len(train))
print(len(val))
print(len(test))

193
49
61


In [17]:
def df_to_datasets(dataframe,shuffle=True,batch_size=32):
    dataframe = dataframe.copy()
    labels = dataframe.pop('target') # 将标签列取出,取出后dataframe中将没有'target'列了
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe),labels)) #ds是拆分成了303个字典组成的组合
    if shuffle:
        ds.shuffle(buffer_size=len(dataframe)) #shuffle的功能为打乱dataset中的元素，它有一个参数buffersize，表示打乱时使用的buffer的大小：
    ds = ds.batch(batch_size) # 按照每份batch_size个，分成（总数/batch_size）个组
    return ds
dataframe = dataframe.copy()
labels = dataframe.pop('target') # 将标签列取出

In [45]:
(dict(dataframe),labels)

({'age': 0      63
  1      67
  2      67
  3      37
  4      41
         ..
  298    52
  299    43
  300    65
  301    48
  302    63
  Name: age, Length: 303, dtype: int64, 'sex': 0      1
  1      1
  2      1
  3      1
  4      0
        ..
  298    1
  299    0
  300    1
  301    1
  302    0
  Name: sex, Length: 303, dtype: int64, 'cp': 0      1
  1      4
  2      4
  3      3
  4      2
        ..
  298    1
  299    4
  300    4
  301    4
  302    4
  Name: cp, Length: 303, dtype: int64, 'trestbps': 0      145
  1      160
  2      120
  3      130
  4      130
        ... 
  298    118
  299    132
  300    135
  301    130
  302    150
  Name: trestbps, Length: 303, dtype: int64, 'chol': 0      233
  1      286
  2      229
  3      250
  4      204
        ... 
  298    186
  299    341
  300    254
  301    256
  302    407
  Name: chol, Length: 303, dtype: int64, 'fbs': 0      1
  1      0
  2      0
  3      0
  4      0
        ..
  298    0
  299    1
  300    0

In [27]:
ds = tf.data.Dataset.from_tensor_slices((dict(dataframe),labels))

In [59]:
len =0
for data in ds:
    print(data)
    len =len+1
    print('=======================')
print(len)

({'age': <tf.Tensor: id=26397, shape=(), dtype=int32, numpy=63>, 'sex': <tf.Tensor: id=26405, shape=(), dtype=int32, numpy=1>, 'cp': <tf.Tensor: id=26400, shape=(), dtype=int32, numpy=1>, 'trestbps': <tf.Tensor: id=26409, shape=(), dtype=int32, numpy=145>, 'chol': <tf.Tensor: id=26399, shape=(), dtype=int32, numpy=233>, 'fbs': <tf.Tensor: id=26402, shape=(), dtype=int32, numpy=1>, 'restecg': <tf.Tensor: id=26404, shape=(), dtype=int32, numpy=2>, 'thalach': <tf.Tensor: id=26408, shape=(), dtype=int32, numpy=150>, 'exang': <tf.Tensor: id=26401, shape=(), dtype=int32, numpy=0>, 'oldpeak': <tf.Tensor: id=26403, shape=(), dtype=float64, numpy=2.3>, 'slope': <tf.Tensor: id=26406, shape=(), dtype=int32, numpy=3>, 'ca': <tf.Tensor: id=26398, shape=(), dtype=int32, numpy=0>, 'thal': <tf.Tensor: id=26407, shape=(), dtype=string, numpy=b'fixed'>}, <tf.Tensor: id=26410, shape=(), dtype=int32, numpy=0>)
({'age': <tf.Tensor: id=26425, shape=(), dtype=int32, numpy=67>, 'sex': <tf.Tensor: id=26433, sh

303


In [31]:
len(dataframe)

303

In [32]:
ds.shuffle(buffer_size=len(dataframe))

<ShuffleDataset shapes: ({age: (), sex: (), cp: (), trestbps: (), chol: (), fbs: (), restecg: (), thalach: (), exang: (), oldpeak: (), slope: (), ca: (), thal: ()}, ()), types: ({age: tf.int32, sex: tf.int32, cp: tf.int32, trestbps: tf.int32, chol: tf.int32, fbs: tf.int32, restecg: tf.int32, thalach: tf.int32, exang: tf.int32, oldpeak: tf.float64, slope: tf.int32, ca: tf.int32, thal: tf.string}, tf.int32)>

In [58]:
len = 0
for data in ds.batch(32): 
    print(data)
    len = len+1
    print('====================')
print(len)

({'age': <tf.Tensor: id=26112, shape=(32,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57, 48,
       54, 48, 49, 64, 58, 58, 58, 60, 50, 58, 66, 43, 40, 69, 60],
      dtype=int32)>, 'sex': <tf.Tensor: id=26120, shape=(32,), dtype=int32, numpy=
array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1], dtype=int32)>, 'cp': <tf.Tensor: id=26115, shape=(32,), dtype=int32, numpy=
array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3, 2, 4, 3, 2, 1, 1,
       2, 3, 4, 3, 3, 1, 4, 4, 1, 4], dtype=int32)>, 'trestbps': <tf.Tensor: id=26124, shape=(32,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150, 110, 140, 130, 130, 110, 150, 120, 132, 130, 120,
       120, 150, 150, 110, 140, 117], dtype=int32)>, 'chol': <tf.Tensor: id=26114, shape=(32,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256