In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import optimizers,layers 

print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/_api/v2/version/__init__.py'>


In [7]:
# 我们定义3个用户及他们的用数字化表示的特征(职业：学生，白领，科学家；  年龄段：18岁以下，18-35岁，35岁以上)：
#用户U1的特征[1,1]（16岁的学生）,用户U2的特征[2,2](25岁的白领),用户U3的特征[3,3]（35岁的科学家）
users = np.array([
    [1,1],
    [1,1],
    [1,1],
    [2,2],
    [2,2],
    [2,2],
    [3,3],
    [3,3],
    [3,3]
])
# 我们定义3部影视作品及它们的用数字化表示的特征(类型（青春校园，职场生活，科幻世界），年代：10年以内，10以前20年以内，20年以前)：
#影视M1的特征[1,1]《少年派》,影视M2的特征[2,2]《穿普拉达的女王》,电影M3的特征[3,3]《2001太空漫游》
movies = np.array([
    [1,1],
    [2,2],
    [3,3],
    [1,1],
    [2,2],
    [3,3],
    [1,1],
    [2,2],
    [3,3]
])
# 这里是3个用户观看三部作品时对作品的评分记录
rates = np.array([
    [15],
    [2],
    [3],
    [4],
    [18],
    [3],
    [2],
    [4],
    [18]
])

# 用于训练用户特征的神经网络
input_users = layers.Input(shape=(2,))
layerU1 = layers.Dense(32,activation='relu')(input_users)
layerU2 = layers.Dense(16,activation='relu')(layerU1)
layerU3 = layers.Dense(16,activation='relu')(layerU2)
layerU4 = layers.Dense(8,activation='relu')(layerU3)

modelUserFeature = keras.models.Model(inputs=[input_users],outputs=layerU4)



# 用于训练影视特征的神经网络
input_movies = layers.Input(shape=(2,))
layerM1 = layers.Dense(32,activation='relu')(input_movies)
layerM2 = layers.Dense(16,activation='relu')(layerM1)
layerM3 = layers.Dense(16,activation='relu')(layerM2)
layerM4 = layers.Dense(8,activation='relu')(layerM3)

modelMovieFeature = keras.models.Model(inputs=[input_movies],outputs=layerM4)

layerMultiply = layers.multiply([modelUserFeature.output,modelMovieFeature.output])


# 最后一层采用进行加和运算:keepdims=True这里要设置为True，不然加和过的那个维度会消失
# out = tf.reduce_sum(layerMultiply,keepdims=True)
#
outlayer = layers.Dense(1,trainable=False, use_bias=False)
outlayer(layerMultiply)
outLayerWeights = np.ones((8,1))
outlayer.set_weights([outLayerWeights])
out = outlayer(layerMultiply)

# 模型初始化
model = keras.models.Model(inputs=[input_users,input_movies],outputs=out)


# 模型参数调整
model.compile(optimizer=keras.optimizers.Adam(0.01,amsgrad=True),loss='mse')
model.summary()


tensorboard =  tf.keras.callbacks.TensorBoard(
    log_dir='/Users/zhenwuzhou/TensorBoardLogs/tensorboardLogs-predict-rates'.format(model.name),
    histogram_freq=1, batch_size=32,
    write_graph=True, write_grads=False, write_images=True,
    embeddings_freq=0, embeddings_layer_names=None,
    embeddings_metadata=None, embeddings_data=None, update_freq=500
)

# 模型训练开始
history = model.fit([users,movies],rates,epochs=1000,callbacks=[tensorboard],use_multiprocessing=False)

Model: "model_14"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_9 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
input_10 (InputLayer)           [(None, 2)]          0                                            
__________________________________________________________________________________________________
dense_36 (Dense)                (None, 32)           96          input_9[0][0]                    
__________________________________________________________________________________________________
dense_40 (Dense)                (None, 32)           96          input_10[0][0]                   
___________________________________________________________________________________________

Epoch 63/1000
9/9 [==============================] - 0s 1ms/sample - loss: 44.0525
Epoch 64/1000
9/9 [==============================] - 0s 1ms/sample - loss: 44.0236
Epoch 65/1000
9/9 [==============================] - 0s 1ms/sample - loss: 44.0080
Epoch 66/1000
9/9 [==============================] - 0s 1ms/sample - loss: 44.0022
Epoch 67/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.9924
Epoch 68/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.9713
Epoch 69/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.9459
Epoch 70/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.9269
Epoch 71/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.9155
Epoch 72/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.9042
Epoch 73/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.8866
Epoch 74/1000
9/9 [==============================] - 0s 1ms/sample - loss: 43.8647
Epoc

Epoch 161/1000
9/9 [==============================] - 0s 1ms/sample - loss: 23.7937
Epoch 162/1000
9/9 [==============================] - 0s 1ms/sample - loss: 23.6620
Epoch 163/1000
9/9 [==============================] - 0s 1ms/sample - loss: 23.4336
Epoch 164/1000
9/9 [==============================] - 0s 1ms/sample - loss: 23.2090
Epoch 165/1000
9/9 [==============================] - 0s 1ms/sample - loss: 23.0209
Epoch 166/1000
9/9 [==============================] - 0s 1ms/sample - loss: 22.8173
Epoch 167/1000
9/9 [==============================] - 0s 1ms/sample - loss: 22.6024
Epoch 168/1000
9/9 [==============================] - 0s 1ms/sample - loss: 22.3277
Epoch 169/1000
9/9 [==============================] - 0s 1ms/sample - loss: 22.1788
Epoch 170/1000
9/9 [==============================] - 0s 1ms/sample - loss: 21.9591
Epoch 171/1000
9/9 [==============================] - 0s 1ms/sample - loss: 21.8824
Epoch 172/1000
9/9 [==============================] - 0s 1ms/sample - loss: 

Epoch 259/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.5365
Epoch 260/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.6353
Epoch 261/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.4002
Epoch 262/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.2371
Epoch 263/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.7165
Epoch 264/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.8153
Epoch 265/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.5715
Epoch 266/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.4221
Epoch 267/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.4663
Epoch 268/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.5486
Epoch 269/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.2167
Epoch 270/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.5090
Epoc

Epoch 357/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.5905e-05
Epoch 358/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.0649e-04
Epoch 359/1000
9/9 [==============================] - 0s 1ms/sample - loss: 7.2659e-05
Epoch 360/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.4266e-05
Epoch 361/1000
9/9 [==============================] - 0s 1ms/sample - loss: 7.5541e-05
Epoch 362/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.2102e-05
Epoch 363/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.3814e-05
Epoch 364/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.1515e-05
Epoch 365/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.4742e-05
Epoch 366/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.6464e-05
Epoch 367/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.1312e-05
Epoch 368/1000
9/9 [=======================

9/9 [==============================] - 0s 2ms/sample - loss: 6.7669e-09
Epoch 452/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.9751e-09
Epoch 453/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.3868e-09
Epoch 454/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.0083e-09
Epoch 455/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.3439e-10
Epoch 456/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.9136e-09
Epoch 457/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.1509e-09
Epoch 458/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.2880e-09
Epoch 459/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.0829e-09
Epoch 460/1000
9/9 [==============================] - 0s 1ms/sample - loss: 7.4087e-10
Epoch 461/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.7795e-09
Epoch 462/1000
9/9 [==============================] - 0s 1

Epoch 546/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.2800e-10
Epoch 547/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.0250e-10
Epoch 548/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.8667e-10
Epoch 549/1000
9/9 [==============================] - 0s 1ms/sample - loss: 8.8935e-11
Epoch 550/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.1390e-12
Epoch 551/1000
9/9 [==============================] - 0s 1ms/sample - loss: 7.8787e-11
Epoch 552/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.5443e-10
Epoch 553/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.2085e-10
Epoch 554/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.5228e-10
Epoch 555/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.0771e-10
Epoch 556/1000
9/9 [==============================] - 0s 1ms/sample - loss: 6.2659e-10
Epoch 557/1000
9/9 [=======================

9/9 [==============================] - 0s 1ms/sample - loss: 4.0338e-09
Epoch 641/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.5858e-09
Epoch 642/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.7654e-09
Epoch 643/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.9456e-09
Epoch 644/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.1805e-09
Epoch 645/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.0972e-09
Epoch 646/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.5912e-09
Epoch 647/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.0202e-09
Epoch 648/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.4939e-09
Epoch 649/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.7741e-09
Epoch 650/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.2701e-09
Epoch 651/1000
9/9 [==============================] - 0s 1

Epoch 737/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.0046
Epoch 738/1000
9/9 [==============================] - 0s 1ms/sample - loss: 6.1222e-04
Epoch 739/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.0018
Epoch 740/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.0034
Epoch 741/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.1496e-04
Epoch 742/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.0015
Epoch 743/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.0025
Epoch 744/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.2584e-04
Epoch 745/1000
9/9 [==============================] - 0s 1ms/sample - loss: 0.0013
Epoch 746/1000
9/9 [==============================] - 0s 2ms/sample - loss: 0.0018
Epoch 747/1000
9/9 [==============================] - 0s 1ms/sample - loss: 6.1345e-05
Epoch 748/1000
9/9 [==============================] - 0s 1ms/sample - l

Epoch 832/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.5057e-08
Epoch 833/1000
9/9 [==============================] - 0s 1ms/sample - loss: 9.8127e-08
Epoch 834/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.2549e-07
Epoch 835/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.7165e-08
Epoch 836/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.8501e-08
Epoch 837/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.6518e-07
Epoch 838/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.2418e-08
Epoch 839/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.9910e-08
Epoch 840/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.1399e-07
Epoch 841/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.5315e-08
Epoch 842/1000
9/9 [==============================] - 0s 1ms/sample - loss: 6.9366e-09
Epoch 843/1000
9/9 [=======================

9/9 [==============================] - 0s 1ms/sample - loss: 2.1264e-10
Epoch 927/1000
9/9 [==============================] - 0s 1ms/sample - loss: 9.3274e-11
Epoch 928/1000
9/9 [==============================] - 0s 2ms/sample - loss: 1.5012e-10
Epoch 929/1000
9/9 [==============================] - 0s 1ms/sample - loss: 3.7892e-10
Epoch 930/1000
9/9 [==============================] - 0s 2ms/sample - loss: 3.0718e-10
Epoch 931/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.1332e-10
Epoch 932/1000
9/9 [==============================] - 0s 1ms/sample - loss: 2.3544e-10
Epoch 933/1000
9/9 [==============================] - 0s 1ms/sample - loss: 4.7469e-10
Epoch 934/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.4594e-10
Epoch 935/1000
9/9 [==============================] - 0s 1ms/sample - loss: 1.8787e-10
Epoch 936/1000
9/9 [==============================] - 0s 1ms/sample - loss: 5.2220e-10
Epoch 937/1000
9/9 [==============================] - 0s 1

In [3]:
# 模型参数调整
model.compile(optimizer=keras.optimizers.Adam(0.0001),loss='mse')
model.summary()

# 模型训练开始
history = model.fit([users,movies],rates,epochs=1000)

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 32)           96          input_1[0][0]                    
__________________________________________________________________________________________________
dense_4 (Dense)                 (None, 32)           96          input_2[0][0]                    
____________________________________________________________________________________________

Epoch 63/1000
9/9 [==============================] - 0s 177us/sample - loss: 19.3204
Epoch 64/1000
9/9 [==============================] - 0s 164us/sample - loss: 19.3203
Epoch 65/1000
9/9 [==============================] - 0s 157us/sample - loss: 19.3202
Epoch 66/1000
9/9 [==============================] - 0s 162us/sample - loss: 19.3201
Epoch 67/1000
9/9 [==============================] - 0s 190us/sample - loss: 19.3201
Epoch 68/1000
9/9 [==============================] - 0s 164us/sample - loss: 19.3200
Epoch 69/1000
9/9 [==============================] - 0s 157us/sample - loss: 19.3200
Epoch 70/1000
9/9 [==============================] - 0s 154us/sample - loss: 19.3200
Epoch 71/1000
9/9 [==============================] - 0s 160us/sample - loss: 19.3200
Epoch 72/1000
9/9 [==============================] - 0s 188us/sample - loss: 19.3200
Epoch 73/1000
9/9 [==============================] - 0s 160us/sample - loss: 19.3200
Epoch 74/1000
9/9 [==============================] - 0s 150us/sam

Epoch 159/1000
9/9 [==============================] - 0s 140us/sample - loss: 19.3196
Epoch 160/1000
9/9 [==============================] - 0s 137us/sample - loss: 19.3196
Epoch 161/1000
9/9 [==============================] - 0s 135us/sample - loss: 19.3196
Epoch 162/1000
9/9 [==============================] - 0s 145us/sample - loss: 19.3196
Epoch 163/1000
9/9 [==============================] - 0s 140us/sample - loss: 19.3196
Epoch 164/1000
9/9 [==============================] - 0s 156us/sample - loss: 19.3196
Epoch 165/1000
9/9 [==============================] - 0s 141us/sample - loss: 19.3196
Epoch 166/1000
9/9 [==============================] - 0s 177us/sample - loss: 19.3196
Epoch 167/1000
9/9 [==============================] - 0s 153us/sample - loss: 19.3196
Epoch 168/1000
9/9 [==============================] - 0s 141us/sample - loss: 19.3196
Epoch 169/1000
9/9 [==============================] - 0s 151us/sample - loss: 19.3196
Epoch 170/1000
9/9 [==============================] - 

Epoch 255/1000
9/9 [==============================] - 0s 177us/sample - loss: 19.3195
Epoch 256/1000
9/9 [==============================] - 0s 254us/sample - loss: 19.3195
Epoch 257/1000
9/9 [==============================] - 0s 187us/sample - loss: 19.3195
Epoch 258/1000
9/9 [==============================] - 0s 173us/sample - loss: 19.3195
Epoch 259/1000
9/9 [==============================] - 0s 144us/sample - loss: 19.3195
Epoch 260/1000
9/9 [==============================] - 0s 146us/sample - loss: 19.3195
Epoch 261/1000
9/9 [==============================] - 0s 205us/sample - loss: 19.3195
Epoch 262/1000
9/9 [==============================] - 0s 171us/sample - loss: 19.3195
Epoch 263/1000
9/9 [==============================] - 0s 138us/sample - loss: 19.3195
Epoch 264/1000
9/9 [==============================] - 0s 228us/sample - loss: 19.3195
Epoch 265/1000
9/9 [==============================] - 0s 169us/sample - loss: 19.3195
Epoch 266/1000
9/9 [==============================] - 

Epoch 351/1000
9/9 [==============================] - 0s 152us/sample - loss: 19.3195
Epoch 352/1000
9/9 [==============================] - 0s 168us/sample - loss: 19.3195
Epoch 353/1000
9/9 [==============================] - 0s 152us/sample - loss: 19.3195
Epoch 354/1000
9/9 [==============================] - 0s 263us/sample - loss: 19.3195
Epoch 355/1000
9/9 [==============================] - 0s 160us/sample - loss: 19.3195
Epoch 356/1000
9/9 [==============================] - 0s 140us/sample - loss: 19.3195
Epoch 357/1000
9/9 [==============================] - 0s 182us/sample - loss: 19.3195
Epoch 358/1000
9/9 [==============================] - 0s 221us/sample - loss: 19.3195
Epoch 359/1000
9/9 [==============================] - 0s 186us/sample - loss: 19.3195
Epoch 360/1000
9/9 [==============================] - 0s 172us/sample - loss: 19.3195
Epoch 361/1000
9/9 [==============================] - 0s 223us/sample - loss: 19.3195
Epoch 362/1000
9/9 [==============================] - 

Epoch 447/1000
9/9 [==============================] - 0s 186us/sample - loss: 19.3195
Epoch 448/1000
9/9 [==============================] - 0s 163us/sample - loss: 19.3195
Epoch 449/1000
9/9 [==============================] - 0s 168us/sample - loss: 19.3195
Epoch 450/1000
9/9 [==============================] - 0s 173us/sample - loss: 19.3195
Epoch 451/1000
9/9 [==============================] - 0s 148us/sample - loss: 19.3195
Epoch 452/1000
9/9 [==============================] - 0s 212us/sample - loss: 19.3195
Epoch 453/1000
9/9 [==============================] - 0s 177us/sample - loss: 19.3195
Epoch 454/1000
9/9 [==============================] - 0s 191us/sample - loss: 19.3195
Epoch 455/1000
9/9 [==============================] - 0s 168us/sample - loss: 19.3195
Epoch 456/1000
9/9 [==============================] - 0s 154us/sample - loss: 19.3195
Epoch 457/1000
9/9 [==============================] - 0s 168us/sample - loss: 19.3195
Epoch 458/1000
9/9 [==============================] - 

Epoch 543/1000
9/9 [==============================] - 0s 161us/sample - loss: 19.3195
Epoch 544/1000
9/9 [==============================] - 0s 197us/sample - loss: 19.3195
Epoch 545/1000
9/9 [==============================] - 0s 171us/sample - loss: 19.3195
Epoch 546/1000
9/9 [==============================] - 0s 162us/sample - loss: 19.3195
Epoch 547/1000
9/9 [==============================] - 0s 227us/sample - loss: 19.3195
Epoch 548/1000
9/9 [==============================] - 0s 158us/sample - loss: 19.3195
Epoch 549/1000
9/9 [==============================] - 0s 159us/sample - loss: 19.3195
Epoch 550/1000
9/9 [==============================] - 0s 163us/sample - loss: 19.3195
Epoch 551/1000
9/9 [==============================] - 0s 139us/sample - loss: 19.3195
Epoch 552/1000
9/9 [==============================] - 0s 197us/sample - loss: 19.3195
Epoch 553/1000
9/9 [==============================] - 0s 358us/sample - loss: 19.3195
Epoch 554/1000
9/9 [==============================] - 

Epoch 639/1000
9/9 [==============================] - 0s 189us/sample - loss: 19.3195
Epoch 640/1000
9/9 [==============================] - 0s 211us/sample - loss: 19.3195
Epoch 641/1000
9/9 [==============================] - 0s 168us/sample - loss: 19.3195
Epoch 642/1000
9/9 [==============================] - 0s 173us/sample - loss: 19.3195
Epoch 643/1000
9/9 [==============================] - 0s 166us/sample - loss: 19.3195
Epoch 644/1000
9/9 [==============================] - 0s 157us/sample - loss: 19.3195
Epoch 645/1000
9/9 [==============================] - 0s 136us/sample - loss: 19.3195
Epoch 646/1000
9/9 [==============================] - 0s 153us/sample - loss: 19.3195
Epoch 647/1000
9/9 [==============================] - 0s 197us/sample - loss: 19.3195
Epoch 648/1000
9/9 [==============================] - 0s 162us/sample - loss: 19.3195
Epoch 649/1000
9/9 [==============================] - 0s 172us/sample - loss: 19.3195
Epoch 650/1000
9/9 [==============================] - 

Epoch 735/1000
9/9 [==============================] - 0s 160us/sample - loss: 19.3195
Epoch 736/1000
9/9 [==============================] - 0s 181us/sample - loss: 19.3195
Epoch 737/1000
9/9 [==============================] - 0s 182us/sample - loss: 19.3195
Epoch 738/1000
9/9 [==============================] - 0s 147us/sample - loss: 19.3195
Epoch 739/1000
9/9 [==============================] - 0s 219us/sample - loss: 19.3195
Epoch 740/1000
9/9 [==============================] - 0s 164us/sample - loss: 19.3195
Epoch 741/1000
9/9 [==============================] - 0s 152us/sample - loss: 19.3195
Epoch 742/1000
9/9 [==============================] - 0s 180us/sample - loss: 19.3195
Epoch 743/1000
9/9 [==============================] - 0s 201us/sample - loss: 19.3195
Epoch 744/1000
9/9 [==============================] - 0s 201us/sample - loss: 19.3195
Epoch 745/1000
9/9 [==============================] - 0s 153us/sample - loss: 19.3195
Epoch 746/1000
9/9 [==============================] - 

Epoch 831/1000
9/9 [==============================] - 0s 138us/sample - loss: 19.3195
Epoch 832/1000
9/9 [==============================] - 0s 145us/sample - loss: 19.3195
Epoch 833/1000
9/9 [==============================] - 0s 139us/sample - loss: 19.3195
Epoch 834/1000
9/9 [==============================] - 0s 153us/sample - loss: 19.3195
Epoch 835/1000
9/9 [==============================] - 0s 220us/sample - loss: 19.3195
Epoch 836/1000
9/9 [==============================] - 0s 184us/sample - loss: 19.3195
Epoch 837/1000
9/9 [==============================] - 0s 147us/sample - loss: 19.3195
Epoch 838/1000
9/9 [==============================] - 0s 172us/sample - loss: 19.3195
Epoch 839/1000
9/9 [==============================] - 0s 171us/sample - loss: 19.3195
Epoch 840/1000
9/9 [==============================] - 0s 158us/sample - loss: 19.3195
Epoch 841/1000
9/9 [==============================] - 0s 182us/sample - loss: 19.3195
Epoch 842/1000
9/9 [==============================] - 

Epoch 927/1000
9/9 [==============================] - 0s 177us/sample - loss: 19.3195
Epoch 928/1000
9/9 [==============================] - 0s 158us/sample - loss: 19.3195
Epoch 929/1000
9/9 [==============================] - 0s 169us/sample - loss: 19.3195
Epoch 930/1000
9/9 [==============================] - 0s 154us/sample - loss: 19.3195
Epoch 931/1000
9/9 [==============================] - 0s 150us/sample - loss: 19.3195
Epoch 932/1000
9/9 [==============================] - 0s 190us/sample - loss: 19.3195
Epoch 933/1000
9/9 [==============================] - 0s 163us/sample - loss: 19.3195
Epoch 934/1000
9/9 [==============================] - 0s 156us/sample - loss: 19.3195
Epoch 935/1000
9/9 [==============================] - 0s 170us/sample - loss: 19.3195
Epoch 936/1000
9/9 [==============================] - 0s 194us/sample - loss: 19.3195
Epoch 937/1000
9/9 [==============================] - 0s 161us/sample - loss: 19.3195
Epoch 938/1000
9/9 [==============================] - 

In [28]:
modelUserFeature.save('/Users/zhenwuzhou/.keras/models/user_feature_model.h5')
modelUserFeature.weights

[<tf.Variable 'dense_76/kernel:0' shape=(2, 32) dtype=float32, numpy=
 array([[-0.10314825, -0.11096928, -0.30070376,  0.04125822,  0.09950072,
          0.02708834, -0.03374193,  0.35501373,  0.2094686 , -0.04772955,
         -0.38435563,  0.24902174,  0.25179988,  0.08035943, -0.06512634,
         -0.00774494,  0.01678789,  0.1884967 , -0.36951834, -0.22555545,
          0.28177723,  0.06614621, -0.1901084 , -0.3621087 ,  0.3904016 ,
          0.00549906, -0.3152385 , -0.22345231, -0.23384145,  0.07290003,
         -0.21436974, -0.29001826],
        [-0.02258244, -0.10690793, -0.3480299 ,  0.42753607, -0.15884566,
         -0.11131981,  0.1841404 ,  0.33421212,  0.44536576, -0.03795615,
          0.01671219, -0.30491173, -0.00083606, -0.26997155,  0.00054363,
         -0.2255193 ,  0.5312435 ,  0.3212508 , -0.14115682, -0.07959715,
         -0.34142733,  0.443467  ,  0.14496085, -0.29642594,  0.14275333,
         -0.06871843,  0.27456   ,  0.36001754,  0.00369453, -0.18861477,
      

In [29]:
modelMovieFeature.save('/Users/zhenwuzhou/.keras/models/movie_feature_model.h5')
modelMovieFeature.weights

[<tf.Variable 'dense_80/kernel:0' shape=(2, 32) dtype=float32, numpy=
 array([[-0.2231395 , -0.03542852, -0.01172527, -0.0526391 , -0.28385547,
         -0.17096499,  0.02575058, -0.4093275 , -0.01548299,  0.29189077,
         -0.38347185,  0.41861546,  0.3673942 ,  0.03270162, -0.30680266,
         -0.2135022 , -0.3288055 , -0.24947116, -0.05565169, -0.11312732,
         -0.3872404 , -0.3630355 , -0.3138195 , -0.04520155,  0.02058812,
          0.0848982 , -0.21966459,  0.43252653,  0.2944133 , -0.17553413,
          0.26886818,  0.33022055],
        [-0.12342453, -0.23064126,  0.03689998, -0.15839556,  0.26113734,
          0.07314592, -0.10225931, -0.291722  , -0.00101808, -0.36834902,
         -0.1613842 , -0.10810151, -0.3245589 , -0.0097217 ,  0.02677086,
         -0.28461093, -0.03312144,  0.17348614, -0.39681992, -0.36638266,
         -0.3955726 ,  0.27324188,  0.07840028, -0.09746245, -0.15202178,
         -0.31583744, -0.2733311 ,  0.0032314 , -0.3836354 ,  0.0550707 ,
      

In [30]:
model.predict([users,movies])

array([[14.999974 ],
       [ 1.9999952],
       [ 2.9999924],
       [ 3.9999852],
       [17.999958 ],
       [ 2.9999926],
       [ 1.9999819],
       [ 3.9999096],
       [18.000078 ]], dtype=float32)

In [26]:
model.save('/Users/zhenwuzhou/.keras/models/predict_movie_rates_model.h5')
model.weights

[<tf.Variable 'dense_21/kernel:0' shape=(2, 32) dtype=float32, numpy=
 array([[ 0.32985118, -0.21811347,  0.23823115, -0.35485062,  0.21786085,
          0.34065115, -0.28533676, -0.13487613,  0.25902614, -0.03041142,
          0.05411965,  0.31681785,  0.18642655,  0.3585151 ,  0.24254099,
          0.04439285,  0.05552078,  0.48884806,  0.11725762, -0.1366387 ,
         -0.11082309,  0.02527035, -0.31174135,  0.10801213, -0.38321167,
          0.3715242 , -0.07395844, -0.08034723,  0.61211514,  0.02983421,
         -0.26355356, -0.21715589],
        [ 0.26644853,  0.18393579, -0.24424003,  0.3337405 , -0.18534106,
          0.03561205, -0.07961699,  0.01734382, -0.29324967, -0.11126062,
          0.29511562, -0.448474  , -0.26063374,  0.37717995, -0.40132034,
          0.21111216,  0.31140357,  0.09057201, -0.18186337, -0.28133714,
          0.12205213,  0.07950092,  0.1075764 ,  0.45022717,  0.22852466,
          0.09190024,  0.23909077, -0.05529235,  0.21319872, -0.12730289,
      

In [ ]:








#下面是加载训练好的模型来进行特征预测和分数预测

In [14]:
load_user_feature_model = keras.models.load_model('/Users/zhenwuzhou/.keras/models/user_feature_model.h5')
load_movie_feature_model = keras.models.load_model('/Users/zhenwuzhou/.keras/models/movie_feature_model.h5')
load_predict_movie_rates_model = keras.models.load_model('/Users/zhenwuzhou/.keras/models/predict_movie_rates_model.h5')


In [20]:
load_user_feature_model.predict([users])

array([[0.1045069 , 1.4584786 , 0.        , 0.        , 2.2036977 ,
        0.21381441, 0.43468085, 0.10873564],
       [0.1045069 , 1.4584786 , 0.        , 0.        , 2.2036977 ,
        0.21381441, 0.43468085, 0.10873564],
       [0.1045069 , 1.4584786 , 0.        , 0.        , 2.2036977 ,
        0.21381441, 0.43468085, 0.10873564],
       [2.0118742 , 1.5019433 , 5.6629243 , 0.        , 0.        ,
        0.        , 1.5225948 , 0.        ],
       [2.0118742 , 1.5019433 , 5.6629243 , 0.        , 0.        ,
        0.        , 1.5225948 , 0.        ],
       [2.0118742 , 1.5019433 , 5.6629243 , 0.        , 0.        ,
        0.        , 1.5225948 , 0.        ],
       [5.3435893 , 0.        , 1.5156603 , 5.4501996 , 0.        ,
        0.        , 1.6711645 , 0.        ],
       [5.3435893 , 0.        , 1.5156603 , 5.4501996 , 0.        ,
        0.        , 1.6711645 , 0.        ],
       [5.3435893 , 0.        , 1.5156603 , 5.4501996 , 0.        ,
        0.        , 1.671164

In [21]:
load_movie_feature_model.predict([movies])

array([[0.        , 0.        , 0.74733937, 0.        , 6.8067393 ,
        0.        , 0.        , 0.        ],
       [0.        , 1.4151587 , 2.7922652 , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 2.0263011 , 0.        , 3.3026328 , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.74733937, 0.        , 6.8067393 ,
        0.        , 0.        , 0.        ],
       [0.        , 1.4151587 , 2.7922652 , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 2.0263011 , 0.        , 3.3026328 , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.74733937, 0.        , 6.8067393 ,
        0.        , 0.        , 0.        ],
       [0.        , 1.4151587 , 2.7922652 , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 2.0263011 , 0.        , 3.3026328 , 0.        ,
        0.        , 0.      

In [16]:
load_predict_movie_rates_model.weights

[<tf.Variable 'dense_21_2/kernel:0' shape=(2, 32) dtype=float32, numpy=
 array([[ 0.32985118, -0.21811347,  0.23823115, -0.35485062,  0.21786085,
          0.34065115, -0.28533676, -0.13487613,  0.25902614, -0.03041142,
          0.05411965,  0.31681785,  0.18642655,  0.3585151 ,  0.24254099,
          0.04439285,  0.05552078,  0.48884806,  0.11725762, -0.1366387 ,
         -0.11082309,  0.02527035, -0.31174135,  0.10801213, -0.38321167,
          0.3715242 , -0.07395844, -0.08034723,  0.61211514,  0.02983421,
         -0.26355356, -0.21715589],
        [ 0.26644853,  0.18393579, -0.24424003,  0.3337405 , -0.18534106,
          0.03561205, -0.07961699,  0.01734382, -0.29324967, -0.11126062,
          0.29511562, -0.448474  , -0.26063374,  0.37717995, -0.40132034,
          0.21111216,  0.31140357,  0.09057201, -0.18186337, -0.28133714,
          0.12205213,  0.07950092,  0.1075764 ,  0.45022717,  0.22852466,
          0.09190024,  0.23909077, -0.05529235,  0.21319872, -0.12730289,
    

In [19]:
load_predict_movie_rates_model.predict([users,movies])

array([[14.999995 ],
       [ 2.0639787],
       [ 2.9553168],
       [ 4.232126 ],
       [17.937874 ],
       [ 3.0433896],
       [ 1.1327126],
       [ 4.2321253],
       [18.000008 ]], dtype=float32)